import type { Metadata } from "next";
import { NavbarDemo } from "@/components/ui/MainNavBar";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tesry",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={
						inter.className +
						" dark:bg-grid-white/[0.2] bg-grid-black/[0.2]  pt-20"
					}>
					<NavbarDemo />
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
